### ISSUE TITLE
Created shortcut not working, wrong target

### ISSUE THREAD

**Issue by Sanderttt** [electron/windows-installer#169]
The created shortcut to my electron app is not working because it's pointing to the wrong directory

Properties of the desktop shortcut:
Target: C:\Users\Win10H64\AppData\Local\ZIEN24\dist.exe
Start in: C:\Users\Win10H64\AppData\Local\ZIEN24\app-0.0.1
The dir where the exe resides: C:\Users\Win10H64\AppData\Local\ZIEN24\app-0.0.1\dist.exe

I'm using the following:
electron: 1.4.15
electron-packager: 8.5.1
electron-winstaller: 2.5.2
electron-squirrel-startup: 1.0.0

Any help would be appreciated

**Comment by Sanderttt** [comment]
from SquirrelSetup.log:
`2017-04-18 17:39:33> ApplyReleasesImpl: About to save shortcut: C:\Users\Win10H64\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\ZIEN24\ZIEN24.lnk (target C:\Users\Win10H64\AppData\Local\ZIEN24\dist.exe, workingDir C:\Users\Win10H64\AppData\Local\ZIEN24\app-0.0.1, args , toastActivatorCSLID 6c1df75b-1070-5d73-b55f-1a9aeb0436d6)
2017-04-18 17:39:33> ApplyReleasesImpl: Creating shortcut for dist.exe => C:\Users\Win10H64\Desktop\ZIEN24.lnk
2017-04-18 17:39:33> ApplyReleasesImpl: About to save shortcut: C:\Users\Win10H64\Desktop\ZIEN24.lnk (target C:\Users\Win10H64\AppData\Local\ZIEN24\dist.exe, workingDir C:\Users\Win10H64\AppData\Local\ZIEN24\app-0.0.1, args , toastActivatorCSLID 6c1df75b-1070-5d73-b55f-1a9aeb0436d6)`

**Comment by tobiasWenger** [comment]
I can confirm this issue.

**Comment by Sanderttt** [comment]
I'm going to try 2 things:
1. Use another Update.exe version
2. Create a vbs file that changes the shortcut and call it within the squirrel events

**Comment by Sanderttt** [comment]
I fixed it. It was a problem in my code.

changed:
`
const exeName = 'dist.exe'; 
spawnUpdate(['--createShortcut', exeName]);
`

to: 
`const exeName = path.resolve(path.join(rootAtomFolder,'app-'+package.version+'/dist.exe'));
spawnUpdate(['--createShortcut', exeName]);`

**Comment by reidmweber** [comment]
I'm having this issue, too. I've tried putting the app version in the exeName but that didn't fix it.

**Comment by reidmweber** [comment]
I finally got it to work. My issue was that my package.version was 
`4.0.1-beta.1`
, but the app folder that gets created is 
`app-4.0.1-beta1`
Notice the missing . between beta and 1.
I just removed the beta.1 for now. Not sure if this is a bug in how Squirrel handles versions

**Comment by whitmer** [comment]
Similar issue, my app directory is "app-17.09.07", and the shortcut that is created is to "AppData\Local\App\app.exe" which starts and then dies. However, if I rename the folder to "app-17.9.7" and update the shortcut's starting directory to match, then everything works swimmingly.

**Comment by Boid-John** [comment]
Hello, can someone explain a possible solution in more detail. I've done everything mentioned in this thread and still have the same issue more details posted here:

https://github.com/electron-userland/electron-builder/issues/2775

**Comment by LeonardoRick** [comment]
@Sanderttt  could you please share with us the value of your `rootAtomFolder` ?
