### ISSUE TITLE
No dice: ENOENT: no such file or directory, open 'resources/app/package.json'

### ISSUE THREAD

**Issue by soichih** [electron/windows-installer#96]
I might be misunderstanding some standard directory structure for all electron app, but I have a simple hello-world app on my local directory (from https://github.com/ungoldman/electron-hello-world) and I can run the app just fine with "electron ." 

When I try to run windows-installer with following script

```
var electronInstaller = require('electron-winstaller');

resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: '.',
    outputDirectory: '~/tmp',
    authors: 'My App Inc.',
    exe: 'myapp.exe'
  });

resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));

```

I get following error message.

```
$ node win.js 
No dice: ENOENT: no such file or directory, open '/home/hayashis/test/electron-hello-world/resources/app/package.json'
```

It looks like I am supposed to put all files under resources/app directory.. But I can't figure out where it comes from. Is it a standard to place everything under resources/app directory?

**Comment by MarshallOfSound** [comment]
You must first use a tool such as `electron-packager` to package the app into the structure that `windows-installer` expects.

**Comment by soichih** [comment]
Ah.. I see.. How would I know!?

I've run electron-packager and it created whole bunch of directories for each architecture. I've updated the electronInstaller.createWindowInstaller() to point to -win32-x64 and saw following error message.

```
$ node win.js 
No dice: spawn mono ENOENT
```

I am guessing windows-installer requires mono? Anyway I did following.

```
sudo apt install mono-runtime
```

When I reran win.js, I got 
```
$ node win.js 
No dice: Failed with exit code: null
Output:
Can't find custom attr constructor image: /home/hayashis/test/electron-hello-world/node_modules/electron-winstaller/vendor/nuget.exe mtoken: 0x0a000a76
Unhandled loader error: 8, (null) System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (null)
* Assertion: should not be reached at loader.c:298

Stacktrace:


Native stacktrace:

	mono() [0x49ff2f]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x113d0) [0x7f5a27c5e3d0]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7f5a278b9418]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7f5a278bb01a]
	mono() [0x630409]
	mono() [0x63069c]
	mono() [0x630833]
	mono() [0x54357a]
	mono(mono_class_from_typeref_checked+0x223) [0x524c63]
	mono() [0x5234ad]
	mono(mono_metadata_parse_mh_full+0x497) [0x5620b7]
	mono() [0x433fd6]
	mono() [0x500b39]
	mono() [0x501fbd]
	mono() [0x425db6]
	mono() [0x426749]
	mono(mono_runtime_invoke+0x3d) [0x5ac68d]
	mono(mono_runtime_exec_main+0x10d) [0x5aea1d]
	mono(mono_main+0x1177) [0x476967]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f5a278a4830]
	mono(_start+0x29) [0x422e79]

Debug info from gdb:

[New LWP 15001]
[New LWP 15000]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f5a27c5dfbb in __waitpid (pid=15002, stat_loc=0x7fff75d5b8fc, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7f5a28784780 (LWP 14999) "mono" 0x00007f5a27c5dfbb in __waitpid (pid=15002, stat_loc=0x7fff75d5b8fc, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x7f5a24715700 (LWP 15001) "Finalizer" 0x00007f5a27c5c867 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7f5a267ff700 (LWP 15000) "mono" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185

Thread 3 (Thread 0x7f5a267ff700 (LWP 15000)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000005fdcdb in ?? ()
#2  0x00007f5a27c546fa in start_thread (arg=0x7f5a267ff700) at pthread_create.c:333
#3  0x00007f5a2798ab5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f5a24715700 (LWP 15001)):
#0  0x00007f5a27c5c867 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x956820) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x956820, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f5a27c5c914 in __new_sem_wait_slow (sem=0x956820, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f5a27c5c9ba in __new_sem_wait (sem=<optimized out>) at sem_wait.c:29
#4  0x0000000000622e06 in mono_sem_wait ()
#5  0x00000000005a5742 in ?? ()
#6  0x0000000000587b2b in ?? ()
#7  0x0000000000629a8c in ?? ()
#8  0x00007f5a27c546fa in start_thread (arg=0x7f5a24715700) at pthread_create.c:333
#9  0x00007f5a2798ab5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f5a28784780 (LWP 14999)):
#0  0x00007f5a27c5dfbb in __waitpid (pid=15002, stat_loc=0x7fff75d5b8fc, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00000000004a0006 in ?? ()
#2  <signal handler called>
#3  0x00007f5a278b9418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#4  0x00007f5a278bb01a in __GI_abort () at abort.c:89
#5  0x0000000000630409 in ?? ()
#6  0x000000000063069c in ?? ()
#7  0x0000000000630833 in ?? ()
#8  0x000000000054357a in ?? ()
#9  0x0000000000524c63 in mono_class_from_typeref_checked ()
#10 0x00000000005234ad in ?? ()
#11 0x00000000005620b7 in mono_metadata_parse_mh_full ()
#12 0x0000000000433fd6 in ?? ()
#13 0x0000000000500b39 in ?? ()
#14 0x0000000000501fbd in ?? ()
#15 0x0000000000425db6 in ?? ()
#16 0x0000000000426749 in ?? ()
#17 0x00000000005ac68d in mono_runtime_invoke ()
#18 0x00000000005aea1d in mono_runtime_exec_main ()
#19 0x0000000000476967 in mono_main ()
#20 0x00007f5a278a4830 in __libc_start_main (main=0x422be0, argc=9, argv=0x7fff75d5d7d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff75d5d7c8) at ../csu/libc-start.c:291
#21 0x0000000000422e79 in _start ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================



```

**Comment by paulcbetts** [comment]
`mono-runtime` is probably not sufficient, try just `apt-get install mono`

**Comment by soichih** [comment]
I've installed mono-devel and now it seems to be doing something, but the program just sits and won't do anything.

```
hayashis@yoga:~/git/kdinstall$ node winstaller.js 
(sits here and nothing happens..)
```

I am running following

```
var electronInstaller = require('electron-winstaller');

resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: '/home/hayashis/tmp/kdinstall-win32-x64',
    outputDirectory: '/home/hayashis/tmp/winx64',
    authors: 'SciApt',
    exe: 'kdinstall.exe'
  });

resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));
```

I have following in my appDirectory

```
hayashis@yoga:~/git/kdinstall$ ls -la /home/hayashis/tmp/kdinstall-win32-x64
total 123500
drwxrwxr-x 4 hayashis hayashis     4096 Jun 17 09:28 .
drwxrwxr-x 3 hayashis hayashis     4096 Jun 17 09:18 ..
-rw-rw-r-- 1 hayashis hayashis       15 Jun 17 09:18 content_resources_200_percent.pak
-rw-rw-r-- 1 hayashis hayashis  9498098 Jun 17 09:18 content_shell.pak
-rw-rw-r-- 1 hayashis hayashis  4173928 Jun 17 09:18 d3dcompiler_47.dll
-rw-rw-r-- 1 hayashis hayashis  2009600 Jun 17 09:18 ffmpeg.dll
-rw-rw-r-- 1 hayashis hayashis 10207936 Jun 17 09:18 icudtl.dat
-rwxrwxr-x 1 hayashis hayashis 78968832 Jun 17 09:18 kdinstall.exe
-rw-rw-r-- 1 hayashis hayashis    13312 Jun 17 09:18 libEGL.dll
-rw-rw-r-- 1 hayashis hayashis  2406912 Jun 17 09:18 libGLESv2.dll
-rw-rw-r-- 1 hayashis hayashis     1075 Jun 17 09:18 LICENSE
-rw-rw-r-- 1 hayashis hayashis   968519 Jun 17 09:18 LICENSES.chromium.html
drwxrwxr-x 2 hayashis hayashis     4096 Jun 17 09:18 locales
-rw-rw-r-- 1 hayashis hayashis   660128 Jun 17 09:18 msvcp120.dll
-rw-rw-r-- 1 hayashis hayashis   963232 Jun 17 09:18 msvcr120.dll
-rw-rw-r-- 1 hayashis hayashis   412130 Jun 17 09:18 natives_blob.bin
-rw-rw-r-- 1 hayashis hayashis 13415936 Jun 17 09:18 node.dll
drwxrwxr-x 3 hayashis hayashis     4096 Jun 17 09:18 resources
-rw-rw-r-- 1 hayashis hayashis   618708 Jun 17 09:18 snapshot_blob.bin
-rw-rw-r-- 1 hayashis hayashis    79209 Jun 17 09:18 ui_resources_200_percent.pak
-rw-rw-r-- 1 hayashis hayashis  1524224 Jun 17 09:28 Update.exe
-rw-rw-r-- 1 hayashis hayashis   356528 Jun 17 09:18 vccorlib120.dll
-rw-rw-r-- 1 hayashis hayashis        6 Jun 17 09:18 version
-rw-rw-r-- 1 hayashis hayashis   107368 Jun 17 09:18 xinput1_3.dll
```

I am running it on CentOS7 with node v4.4.4.

**Comment by acepsaepudin** [comment]
@soichih your problem same with me :(

**Comment by vforeman** [comment]
im stuck at the same place too. 
made a gulp task for the build and its just hanging.
`gulp.task('winstaller',()=>{
  resultPromise = electronWinstaller.createWindowsInstaller({
    appDirectory: './wearemarcus-win32-x64',
    outputDirectory: './build/installer64',
    authors: 'Victor Foreman',
    exe: 'wearemarcus.exe'
  });
  resultPromise.then(() => console.log("It worked!"), (e) => console.log(`No dice: ${e.message}`));
})`

output:

`gulp winstaller                                                        
(node:28462) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[14:21:51] Using gulpfile ~/Development/wam/gulpfile.js
[14:21:51] Starting 'winstaller'...
[14:21:51] Finished 'winstaller' after 2.16 ms
`

**Comment by soichih** [comment]
I just tried the latest version and everything works now.

**Comment by antonkarsten** [comment]
I had the same problems (on ubuntu). Two things solved it for me 
1) install mono (http://www.mono-project.com/download/#download-lin)
2) make sure you build with electron-packager using the --asar=true switch (I had turned it of to be able to troubleshoot the result from the packager)

**Comment by hutch120** [comment]
If you are just getting started, consider using electron-forge instead.
https://github.com/electron-userland/electron-forge

**Comment by radi-cho** [comment]
similar issue #236

**Comment by MarshallOfSound** [comment]
Hey 👋 

This issue is being closed as it is stale.  This normally means that the issue has been fixed in newer versions or this issue or no longer impacting you.  If this is not the case please feel free to comment with and @ mention me and we can revisit this.

**Comment by qq1209974887** [comment]
@MarshallOfSound  The problem still exists and is difficult to solve.

**Comment by LeonardoRick** [comment]
@MarshallOfSound the problem still exists. Should we use electron-forge instead? I thought this  package was so much more complete and customizable
